services:
  pg:
    container_name: mapstudio-pg
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=mapstudio
      - POSTGRES_PASSWORD=mapstudio_password #! change this in prod
      - POSTGRES_DB=mapstudio
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      mars:
        ipv4_address: 10.10.1.2

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      mars:
        ipv4_address: 10.10.1.4
    ports:
      - "2781:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ericsison.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password

  # Activate redis when needed
  # redis:
  #   image: redis:alpine3.20
  #   container_name: mapstudio-redis
  #   restart: always
  #   healthcheck:
  #     test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
  #     interval: 1s
  #     timeout: 3s
  #     retries: 5
  #   command: /bin/sh -c "redis-server --requirepass redis_password"
  #   ports:
  #     - "6379:6379"

networks:
  mars:
    name: mars
    ipam:
      driver: default
      config:
        - subnet: "10.10.1.0/24"
